///////////////////////////////////////////////////////////
//  classe_communication.cs
//  Implementation of the Class messagerie
//  Generated by Enterprise Architect
//  Created on:      30-avr.-2026 09:31:52
//  Original author: Matheo
///////////////////////////////////////////////////////////


using System;
using System.Net;
using System.Net.Mail;

namespace Package1 {

    /// Gère la configuration et l'envoi automatique d'emails via le protocole SMTP.
    public class messagerie {

        // Paramètres de connexion au serveur de messagerie
        private string expediteur;
        private string mot_de_passe;
        private string serveurSMTP;
        private string utilisateur;
        private int port;

        public Package1.Systbiblio m_Systbiblio;


        /// Constructeur surchargé servant à l’initialisation de la classe.
        public messagerie(string _serveurSMTP, string _utilisateur, string _mot_de_passe, string _expediteur, int _port) {
            this.serveurSMTP = _serveurSMTP;
            this.utilisateur = _utilisateur;
            this.mot_de_passe = _mot_de_passe;
            this.expediteur = _expediteur;
            this.port = _port;
        }


        /// Méthode utilisée afin d’envoyer le mail au destinataire.
        public bool envoyer(string _destinataire, string _objet, string _message) {
            try { 
                // Création et configuration de l'e-mail (Expéditeur, Destinataire, Sujet, Corps)
                using (MailMessage messageMail = new MailMessage()) {
                    messageMail.From = new MailAddress(this.expediteur);
                    messageMail.To.Add(_destinataire);
                    messageMail.Subject = _objet;
                    messageMail.Body = _message;

                    // Initialisation du client SMTP
                    using (SmtpClient smtp = new SmtpClient(this.serveurSMTP, this.port)) {
                        smtp.Credentials = new NetworkCredential(this.utilisateur, this.mot_de_passe);
                        smtp.EnableSsl = true; 
                        
                        smtp.Send(messageMail); // Envoi effectif
                    }
                }
                return true; // Succès de l'envoi
            }
            catch (Exception ex) {
                // Capture des pannes et journalisation de l'erreur
                Console.WriteLine("Erreur d'envoi SMTP : " + ex.Message);
                return false; // Échec de l'envoi
            }
        }
    }
}
